# Generated by Django 3.1.2 on 2020-11-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=2)),
                ('year', models.CharField(max_length=4, null=True)),
                ('state_code', models.CharField(db_index=True, max_length=2)),
                ('office_code', models.CharField(db_index=True, max_length=3)),
                ('district_no', models.CharField(max_length=2, null=True)),
                ('asterisk', models.CharField(max_length=1, null=True)),
                ('candidate_vote', models.CharField(max_length=8, null=True)),
                ('election_month', models.CharField(max_length=2, null=True)),
                ('election_type', models.CharField(max_length=2, null=True)),
                ('party_code', models.CharField(db_index=True, max_length=4, null=True)),
                ('name', models.CharField(db_index=True, max_length=50)),
            ],
        ),
    ]
