# Generated by Django 3.1.2 on 2020-11-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='state',
            name='area',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='stateoffice',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
