version: '3'

services:
  db:
    image: postgres:9.6.11
    restart: unless-stopped
    env_file: env
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    env_file: env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
