# Generated by Django 2.1.3 on 2018-11-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spelling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='spelling',
            field=models.CharField(max_length=30),
        ),
    ]
