# Generated by Django 2.1.3 on 2018-11-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spelling', '0002_auto_20181120_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='spelling',
            field=models.CharField(max_length=50),
        ),
    ]
